module.exports = [
  { name: 'vue', library: 'Vue', js: 'https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/vue/2.6.10/vue.min.js', css: '' },
  { name: 'vue-i18n', library: 'VueI18n', js: 'https://lf3-cdn-tos.bytecdntp.com/cdn/expire-1-M/vue-i18n/8.15.1/vue-i18n.min.js', css: '' },
  { name: 'vue-router', library: 'VueRouter', js: 'https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/vue-router/3.1.3/vue-router.min.js', css: '' },
  { name: 'vuex', library: 'Vuex', js: 'https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/vuex/3.1.2/vuex.min.js', css: '' },
  { name: 'axios', library: 'axios', js: 'https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/axios/0.19.0/axios.min.js', css: '' },
  { name: 'better-scroll', library: 'BScroll', js: 'https://unpkg.com/better-scroll@1.15.2/dist/bscroll.min.js', css: '' },
  { name: 'axios-mock-adapter', library: 'AxiosMockAdapter', js: 'https://unpkg.com/axios-mock-adapter@1.18.1/dist/axios-mock-adapter.min.js', css: '' },
  { name: 'element-ui', library: 'ELEMENT', js: 'https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/element-ui/2.13.1/index.js', css: 'https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/element-ui/2.13.0/theme-chalk/index.css' },
  { name: 'lodash', library: '_', js: 'https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/lodash.js/4.17.15/lodash.min.js', css: '' },
  { name: 'ua-parser-js', library: 'UAParser', js: 'https://unpkg.com/ua-parser-js@0.7.20/dist/ua-parser.min.js', css: '' },
  { name: 'js-cookie', library: 'Cookies', js: 'https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/js-cookie/2.2.1/js.cookie.min.js', css: '' },
  { name: 'nprogress', library: 'NProgress', js: 'https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/nprogress/0.2.0/nprogress.min.js', css: 'https://lf3-cdn-tos.bytecdntp.com/cdn/expire-1-M/nprogress/0.2.0/nprogress.min.css' },
  { name: 'dayjs', library: 'dayjs', js: 'https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/dayjs/1.8.17/dayjs.min.js', css: '' },
  { name: 'fuse.js', library: 'Fuse', js: 'https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/fuse.js/5.2.3/fuse.min.js', css: '' },
  { name: 'hotkeys-js', library: 'hotkeys', js: 'https://unpkg.com/hotkeys-js@3.7.3/dist/hotkeys.min.js', css: '' },
  { name: 'qs', library: 'Qs', js: 'https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/qs/6.9.1/qs.min.js', css: '' },
  { name: 'lowdb', library: 'low', js: 'https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/lowdb/1.0.0/low.min.js', css: '' },
  { name: 'lowdb/adapters/LocalStorage', library: 'LocalStorage', js: 'https://lf3-cdn-tos.bytecdntp.com/cdn/expire-1-M/lowdb/1.0.0/LocalStorage.min.js', css: '' },
  { name: 'screenfull', library: 'screenfull', js: 'https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/screenfull.js/5.0.2/screenfull.min.js', css: '' },
  { name: 'sortablejs', library: 'Sortable', js: 'https://unpkg.com/sortablejs@1.10.1/Sortable.min.js', css: '' }
]
